// <auto-generated />
using System;
using FluffyPaw_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FluffyPaw_Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241004063016_FluffyPaw")]
    partial class FluffyPaw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4070), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "4CC311E68571B9DB7EE9811B2D0215C97B48824469D3BF110875C97F63A90071CE2358E142222190D91A1D7C5E7DA6E4816052D5DF41B050CA01C7112BB48176",
                            RoleName = "Admin",
                            Status = 1,
                            Username = "FluffyPaw"
                        },
                        new
                        {
                            Id = 2L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4074), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "StoreManager",
                            Status = 1,
                            Username = "test1"
                        },
                        new
                        {
                            Id = 3L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4076), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "StoreManager",
                            Status = 1,
                            Username = "test2"
                        },
                        new
                        {
                            Id = 4L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4078), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "Staff",
                            Status = 1,
                            Username = "test3"
                        },
                        new
                        {
                            Id = 5L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4080), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "Staff",
                            Status = 1,
                            Username = "test4"
                        },
                        new
                        {
                            Id = 6L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4083), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "PetOwner",
                            Status = 1,
                            Username = "test5"
                        },
                        new
                        {
                            Id = 7L,
                            Avatar = "https://d1hjkbq40fs2x4.cloudfront.net/2016-01-31/files/1045.jpg",
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4131), new TimeSpan(0, 7, 0, 0, 0)),
                            Email = "test@gmail.com",
                            Password = "2757CB3CAFC39AF451ABB2697BE79B4AB61D63D74D85B0418629DE8C26811B529F3F3780D0150063FF55A2BEEE74C4EC102A2A2731A1F1F7F10D473AD18A6A87",
                            RoleName = "PetOwner",
                            Status = 1,
                            Username = "test6"
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.BehaviorCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BehaviorCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Chạy vòng tròn trước khi nằm xuống"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Liếm mặt chủ"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Rung lắc đuôi khi vui mừng"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Gầm gừ khi cảm thấy bị đe dọa"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Cào móng để đánh dấu lãnh thổ"
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Checkin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("CheckinTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("StoreServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("StoreServiceId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Checkin = false,
                            CheckinTime = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Cost = 100000.0,
                            CreateDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4843), new TimeSpan(0, 7, 0, 0, 0)),
                            Description = "test",
                            EndTime = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4845), new TimeSpan(0, 7, 0, 0, 0)),
                            PaymentMethod = "PayOS",
                            PetId = 1L,
                            StartTime = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4844), new TimeSpan(0, 7, 0, 0, 0)),
                            Status = "Accept",
                            StoreServiceId = 1L
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.BookingRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PetOwnerId");

                    b.ToTable("BookingRatings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookingId = 1L,
                            Description = "test",
                            PetOwnerId = 1L,
                            Status = true,
                            Vote = 0
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Brand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BrandEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessLicense")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MST")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 2L,
                            Address = "test",
                            BrandEmail = "test1@gmail.com",
                            BusinessLicense = "None",
                            Hotline = "0123456789",
                            Logo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsGufmy584u5_GDdLQaFiguxn8Qc5ILIZ7yA&s",
                            MST = "None",
                            Name = "StoreA",
                            Status = true
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 3L,
                            Address = "test",
                            BrandEmail = "test1@gmail.com",
                            BusinessLicense = "None",
                            Hotline = "0123456789",
                            Logo = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTepBxTlZftnBKdB6N4gQdZLF0W8ISlHdkA&s",
                            MST = "None",
                            Name = "StoreB",
                            Status = true
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Certificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Certificates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Description = "None",
                            File = "test",
                            Name = "Certificate of Excellence in Pet Grooming",
                            ServiceId = 4L
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastMessege")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("StoreId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("DeleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Files", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Identification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Identifications");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.MessageFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageFiles");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergy")
                        .HasColumnType("longtext");

                    b.Property<long>("BehaviorCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Decription")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsNeuter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MicrochipNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetOwnerId")
                        .HasColumnType("bigint");

                    b.Property<long>("PetTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BehaviorCategoryId");

                    b.HasIndex("PetOwnerId");

                    b.HasIndex("PetTypeId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Allergy = "None",
                            BehaviorCategoryId = 1L,
                            Decription = "test",
                            Dob = new DateTimeOffset(new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            IsNeuter = true,
                            MicrochipNumber = "None",
                            Name = "LuLu",
                            PetOwnerId = 1L,
                            PetTypeId = 1L,
                            Sex = "Male",
                            Status = "Available",
                            Weight = 6.5f
                        },
                        new
                        {
                            Id = 2L,
                            Allergy = "None",
                            BehaviorCategoryId = 2L,
                            Decription = "test1",
                            Dob = new DateTimeOffset(new DateTime(2022, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 7, 0, 0, 0)),
                            IsNeuter = false,
                            MicrochipNumber = "None",
                            Name = "MeowMeow",
                            PetOwnerId = 2L,
                            PetTypeId = 18L,
                            Sex = "FeMale",
                            Status = "Unavailable",
                            Weight = 5f
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.PetCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PetCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Cat"
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.PetOwner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("Dob")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reputation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PetOwners");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 6L,
                            Address = "test",
                            Dob = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4359), new TimeSpan(0, 7, 0, 0, 0)),
                            FullName = "Test",
                            Gender = "Male",
                            Phone = "1234567890",
                            Reputation = "Good"
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 7L,
                            Address = "test",
                            Dob = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4362), new TimeSpan(0, 7, 0, 0, 0)),
                            FullName = "Test",
                            Gender = "Male",
                            Phone = "0123456789",
                            Reputation = "Good"
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.PetType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PetCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PetCategoryId");

                    b.ToTable("PetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Image = "None",
                            Name = "Chó Chihuahua",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Image = "None",
                            Name = "Chó Bắc Kinh",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Image = "None",
                            Name = "Chó Bắc Kinh lai Nhật",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Image = "None",
                            Name = "Chó Dachshund (Lạp Xưởng/Xúc Xích)",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Image = "None",
                            Name = "Chó Phú Quốc",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Image = "None",
                            Name = "Chó Poodle",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Image = "None",
                            Name = "Chó Pug",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Image = "None",
                            Name = "Chó Alaska",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Image = "None",
                            Name = "Chó Husky",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Image = "None",
                            Name = "Chó Samoyed",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Image = "None",
                            Name = "Chó Pomeranian (Phốc sóc)",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Image = "None",
                            Name = "Chó Beagle",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Image = "None",
                            Name = "Chó Shiba Inu",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            Image = "None",
                            Name = "Chó Golden Retriever",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            Image = "None",
                            Name = "Chó Becgie",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            Image = "None",
                            Name = "Chó Corgi",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 17L,
                            Image = "None",
                            Name = "Chó Mông Cộc",
                            PetCategoryId = 1L
                        },
                        new
                        {
                            Id = 18L,
                            Image = "None",
                            Name = "Mèo Xiêm",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            Image = "None",
                            Name = "Mèo Anh lông ngắn",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Image = "None",
                            Name = "Mèo Anh lông dài",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            Image = "None",
                            Name = "Mèo Ai Cập",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            Image = "None",
                            Name = "Mèo Ba Tư",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            Image = "None",
                            Name = "Mèo Bali",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            Image = "None",
                            Name = "Mèo Bengal",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            Image = "None",
                            Name = "Mèo Scottish Fold",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            Image = "None",
                            Name = "Mèo Munchkin",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            Image = "None",
                            Name = "Mèo mướp",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            Image = "None",
                            Name = "Mèo Ragdoll",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 29L,
                            Image = "None",
                            Name = "Mèo Maine Coon",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            Image = "None",
                            Name = "Mèo Angora",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 31L,
                            Image = "None",
                            Name = "Mèo Laperm",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 32L,
                            Image = "None",
                            Name = "Mèo Somali",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 33L,
                            Image = "None",
                            Name = "Mèo Toyger",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            Image = "None",
                            Name = "Mèo Turkish Van",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 35L,
                            Image = "None",
                            Name = "Mèo Miến Điện",
                            PetCategoryId = 2L
                        },
                        new
                        {
                            Id = 36L,
                            Image = "None",
                            Name = "Mèo Exotic",
                            PetCategoryId = 2L
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BookingCount")
                        .HasColumnType("int");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<double>("Cost")
                        .HasColumnType("double");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ServiceTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("TotalRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookingCount = 0,
                            BrandId = 1L,
                            Cost = 100000.0,
                            Description = "test",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTepBxTlZftnBKdB6N4gQdZLF0W8ISlHdkA&s",
                            Name = "Grooming",
                            ServiceTypeId = 1L,
                            Status = true,
                            TotalRating = 0f
                        },
                        new
                        {
                            Id = 2L,
                            BookingCount = 0,
                            BrandId = 1L,
                            Cost = 200000.0,
                            Description = "test",
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTepBxTlZftnBKdB6N4gQdZLF0W8ISlHdkA&s",
                            Name = "Vaccine",
                            ServiceTypeId = 2L,
                            Status = true,
                            TotalRating = 0f
                        },
                        new
                        {
                            Id = 3L,
                            BookingCount = 0,
                            BrandId = 1L,
                            Cost = 100000.0,
                            Description = "test",
                            Duration = new TimeSpan(0, 0, 0, 0, 0),
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTepBxTlZftnBKdB6N4gQdZLF0W8ISlHdkA&s",
                            Name = "Hotel",
                            ServiceTypeId = 1L,
                            Status = true,
                            TotalRating = 0f
                        },
                        new
                        {
                            Id = 4L,
                            BookingCount = 0,
                            BrandId = 1L,
                            Cost = 500000.0,
                            Description = "test",
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxTepBxTlZftnBKdB6N4gQdZLF0W8ISlHdkA&s",
                            Name = "Training",
                            ServiceTypeId = 2L,
                            Status = true,
                            TotalRating = 0f
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Grooming"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Vaccine"
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Store", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("TotalRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BrandId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 6L,
                            Address = "aaa",
                            BrandId = 1L,
                            Name = "Name",
                            Phone = "0192837465",
                            Status = false,
                            TotalRating = 5f
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 7L,
                            Address = "aaa",
                            BrandId = 2L,
                            Name = "Name",
                            Phone = "0192837465",
                            Status = false,
                            TotalRating = 5f
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.StoreFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreFiles");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.StoreService", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CurrentPetOwner")
                        .HasColumnType("int");

                    b.Property<int>("LimitPetOwner")
                        .HasColumnType("int");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StoreId");

                    b.ToTable("StoreServices");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CurrentPetOwner = 0,
                            LimitPetOwner = 5,
                            ServiceId = 1L,
                            StartTime = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4816), new TimeSpan(0, 7, 0, 0, 0)),
                            Status = "Acepted",
                            StoreId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CurrentPetOwner = 0,
                            LimitPetOwner = 10,
                            ServiceId = 2L,
                            StartTime = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4819), new TimeSpan(0, 7, 0, 0, 0)),
                            Status = "Acepted",
                            StoreId = 2L
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Tracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Trackings");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookingId = 1L,
                            Description = "test",
                            Status = true,
                            UploadDate = new DateTimeOffset(new DateTime(2024, 10, 4, 13, 30, 16, 274, DateTimeKind.Unspecified).AddTicks(4876), new TimeSpan(0, 7, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.TrackingFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<long>("TrackingId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TrackingId");

                    b.ToTable("TrackingFiles");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.VaccineHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("NextVaccineDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("PetCurrentWeight")
                        .HasColumnType("float");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("VaccineDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("VaccineHistories");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Voucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<double>("Balance")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccountId = 1L,
                            Balance = 1000000.0
                        },
                        new
                        {
                            Id = 2L,
                            AccountId = 2L,
                            Balance = 0.0
                        },
                        new
                        {
                            Id = 3L,
                            AccountId = 3L,
                            Balance = 0.0
                        },
                        new
                        {
                            Id = 4L,
                            AccountId = 6L,
                            Balance = 100.0
                        },
                        new
                        {
                            Id = 5L,
                            AccountId = 7L,
                            Balance = 100.0
                        });
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Booking", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.StoreService", "StoreService")
                        .WithMany()
                        .HasForeignKey("StoreServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("StoreService");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.BookingRating", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.PetOwner", "PetOwner")
                        .WithMany()
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PetOwner");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Brand", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Certificate", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Service", "Service")
                        .WithMany("Certificate")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Conversation", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.PetOwner", "PetOwner")
                        .WithMany()
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetOwner");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Identification", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.MessageFile", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.ConversationMessage", "ConversationMessage")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationMessage");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Notification", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Pet", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.BehaviorCategory", "BehaviorCategory")
                        .WithMany()
                        .HasForeignKey("BehaviorCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.PetOwner", "PetOwner")
                        .WithMany()
                        .HasForeignKey("PetOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.PetType", "PetType")
                        .WithMany()
                        .HasForeignKey("PetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BehaviorCategory");

                    b.Navigation("PetOwner");

                    b.Navigation("PetType");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.PetOwner", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.PetType", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.PetCategory", "PetCategory")
                        .WithMany()
                        .HasForeignKey("PetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PetCategory");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Service", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Store", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.StoreFile", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.StoreService", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Tracking", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.TrackingFile", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FluffyPaw_Domain.Entities.Tracking", "Tracking")
                        .WithMany()
                        .HasForeignKey("TrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Files");

                    b.Navigation("Tracking");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.VaccineHistory", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Voucher", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Wallet", b =>
                {
                    b.HasOne("FluffyPaw_Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FluffyPaw_Domain.Entities.Service", b =>
                {
                    b.Navigation("Certificate");
                });
#pragma warning restore 612, 618
        }
    }
}
